extends Node

signal request_attack
signal player_attack_villager
signal ork_start_attack
signal ork_attack
signal player_die
signal player_finished_attack
signal ork_back_default
signal full_attack
signal crescent_captain_attack
signal crescent_captain_die
signal show_final_scene
